stages:
  - build

build image and push to registry:
  stage: build
  image: docker:latest
  script:
    - apk add curl
    - curl https://registry.gitlab.sirok.space/v2/
    - echo $CI_DEPLOY_USER
    - echo $CI_DEPLOY_PASSWORD
    - docker login registry.gitlab.sirok.space -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD
    - docker build -t registry.gitlab.sirok.space/spo/comfort-zone/comfort-zone-frontend:latest .
    - docker push registry.gitlab.sirok.space/spo/comfort-zone/comfort-zone-frontend:latest

