image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build

build image and push to registry:
  stage: build
  before_script:
    - apt-get install curl -y
  script:
    - curl registry.gitlab.sirok.space
    - docker login registry.gitlab.sirok.space -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD
    - docker build -t registry.gitlab.sirok.space/spo/comfort-zone/comfort-zone-frontend:latest .
    - docker push registry.gitlab.sirok.space/spo/comfort-zone/comfort-zone-frontend:latest

