stages:
  - build

build image and push to registry:
  stage: build
  script:
    - export DOCKER_BUILDKIT=1
    - apk add curl
    - curl -v https://registry.gitlab.sirok.space/v2/
    - curl -v https://gitlab.sirok.space/jwt/auth
    - echo $CI_DEPLOY_USER
    - echo $CI_DEPLOY_PASSWORD
    - echo $CI_DEPLOY_PASSWORD | docker --debug login registry.gitlab.sirok.space -u $CI_DEPLOY_USER --password-stdin
    - docker build -t registry.gitlab.sirok.space/spo/comfort-zone/comfort-zone-frontend:latest .
    - docker push registry.gitlab.sirok.space/spo/comfort-zone/comfort-zone-frontend:latest

