import "./globals.css";
import { Inter } from "next/font/google";
import { ReduxProvider } from "@/components/ReduxProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className} style={{ margin: 0 }}>
				<ReduxProvider>
					<AntdRegistry>
						<div className="MainPage">
							<Header />
							{children}
							<Footer/>
						</div>
					</AntdRegistry>
				</ReduxProvider>
			</body>
		</html>
	);
}
